apiVersion: batch/v1
kind: CronJob
metadata:
  name: github-app-secret
spec:
  schedule: "*/30 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: "github-app-secret"
          containers:
            - name: gh-app-secret
              image: darkowlzz/gh-app-secret
              imagePullPolicy: IfNotPresent
              args:
                - "-v=3"
                - --appID=284897
                - --installationID=33438093
                - --privateKeyPath=/etc/secret-volume/privatekey.pem
                - --secretName=my-app-secret
              env:
                - name: NAMESPACE
                  valueFrom:
                    fieldRef:
                      fieldPath: metadata.namespace
              securityContext:
                allowPrivilegeEscalation: false
              volumeMounts:
                - mountPath: /etc/secret-volume
                  name: secret-volume
          restartPolicy: Never
          volumes:
            - name: secret-volume
              secret:
                secretName: github-app-private-key
