apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: vcluster
resources:
  - rbac.yaml
  - cronjob.yaml
images:
  - name: darkowlzz/gh-app-secret
    newName: kingdonb/gh-app-secret
    newTag: ff26f85d
